kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
  namespace: spark
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: worker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7077